// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClc-dxuDYWVHPopwYeTLwBwqTdl40yt5E',
    appId: '1:176989266821:web:e38028fc414a9ea22e1aec',
    messagingSenderId: '176989266821',
    projectId: 'ai-tutor-app-a634e',
    authDomain: 'ai-tutor-app-a634e.firebaseapp.com',
    storageBucket: 'ai-tutor-app-a634e.firebasestorage.app',
    measurementId: 'G-5BQ2SWKPX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr1MGvBJ3nggRX3RJYQUyomQs_yNCbYi0',
    appId: '1:176989266821:android:e25ddb30a2cfe1da2e1aec',
    messagingSenderId: '176989266821',
    projectId: 'ai-tutor-app-a634e',
    storageBucket: 'ai-tutor-app-a634e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6571EhXYlKISFjl6o0B6NJ_RWUBaT7L8',
    appId: '1:176989266821:ios:81f251167d58553d2e1aec',
    messagingSenderId: '176989266821',
    projectId: 'ai-tutor-app-a634e',
    storageBucket: 'ai-tutor-app-a634e.firebasestorage.app',
    iosBundleId: 'com.example.comind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6571EhXYlKISFjl6o0B6NJ_RWUBaT7L8',
    appId: '1:176989266821:ios:81f251167d58553d2e1aec',
    messagingSenderId: '176989266821',
    projectId: 'ai-tutor-app-a634e',
    storageBucket: 'ai-tutor-app-a634e.firebasestorage.app',
    iosBundleId: 'com.example.comind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClc-dxuDYWVHPopwYeTLwBwqTdl40yt5E',
    appId: '1:176989266821:web:746735d499e8ef1f2e1aec',
    messagingSenderId: '176989266821',
    projectId: 'ai-tutor-app-a634e',
    authDomain: 'ai-tutor-app-a634e.firebaseapp.com',
    storageBucket: 'ai-tutor-app-a634e.firebasestorage.app',
    measurementId: 'G-NFMJ2ZKL9P',
  );
}
